apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "centrifugo.fullname" . }}-config
  labels:
    app: {{ include "centrifugo.name" . }}
    chart: {{ include "centrifugo.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  config.json: |-
{{ toJson .Values.config| indent 4 }}
