{{- if .Values.rbac.enabled -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "centrifugo.fullname" . }}-{{ .Release.Namespace }}
  labels:
    app: {{ include "centrifugo.name" . }}
    chart: {{ include "centrifugo.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
rules:
- apiGroups:
  - ""
  resources:
  - endpoints
  - pods
  - services
  - secrets
  verbs:
  - get
  - list
  - watch
{{- end -}}
