{{- if .Values.internalService.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "centrifugo.fullname" . }}-internal
  labels:
    {{- include "centrifugo.labels" . | nindent 4 }}
  {{- with .Values.internalService.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.internalService.type }}
  ports:
    - port: {{ .Values.internalService.port }}
      targetPort: http-internal
      protocol: TCP
      name: http-internal
      {{- if (and (eq .Values.internalService.type "NodePort") (not (empty .Values.internalService.nodePort))) }}
      nodePort: {{ .Values.internalService.nodePort }}
      {{- end }}
  selector:
    {{- include "centrifugo.selectorLabels" . | nindent 4 }}
{{- end }}
