replicaCount: 1

image:
  repository: centrifugo/centrifugo
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  port: 8000
  type: ClusterIP
  # Static NodePort, if set.
  # nodePort: 30100
  annotations: {}

internalService:
  enabled: true
  port: 9000
  type: ClusterIP
  # Static NodePort, if set.
  # nodePort: 30100
  annotations: {}
    # prometheus.io/scrape: "true"
    # prometheus.io/path: "/metrics"
    # prometheus.io/port: "9000"

grpcService:
  enabled: false
  port: 10000
  type: ClusterIP
  # Static NodePort, if set.
  # nodePort: 30100
  annotations: {}

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
    #
    # To run on custom path:
    # nginx.ingress.kubernetes.io/rewrite-target: /$2
  hosts: []
    # - host: centrifugo.local
    #   paths:
    #     - /
    # - host: centrifugo-with-prefix.local
    #   paths:
    #     - /test(/|$)(.*)
  # https://kubernetes.github.io/ingress-nginx/examples/tls-termination/
  tls: []
    # - secretName: centrifugo-example-tls
    #   hosts:
    #     - centrifugo.local

resources: {}

serviceAccount:
  # Specifies whether a service account should be created.
  create: true
  # Annotations to add to the service account.
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template.
  name: ""

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

terminationGracePeriodSeconds: 30

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000
  #
  # You can also tune sysctl, ex.:
  # sysctls:
  #   - name: net.core.somaxconn
  #     value: "2048"

deploymentStrategy: {}
  # type: RollingUpdate
  # rollingUpdate:
  #   maxSurge: 0
  #   maxUnavailable: 1

serviceMonitor:
  enabled: false
  # namespace: monitoring
  # interval: 10

  # Set labels for the ServiceMonitor, use this to define your scrape label for Prometheus Operator.
  labels: {}

nodeSelector: {}

tolerations: []

affinity: {}

config:
  # Engine to use. Default memory engine allows running only one Centrifugo pod.
  # Scale to many pods with Redis engine or Nats broker. Refer to Centrifugo
  # documentation: https://centrifugal.github.io/centrifugo/server/engines/
  engine: "memory"

  # Broker to use, not used by default.
  broker: ""

  # Use offset protocol field.
  v3_use_offset: true

  # Enable admin web interface by default.
  admin: true

  # Array of namespaces.
  namespaces: []

secrets:
  # Secret key for HMAC tokens.
  tokenHmacSecretKey: ""

  # Admin password used to protect access to web interface.
  adminPassword: ""

  # Admin secret used to create auth tokens on user login into admin web interface.
  adminSecret: ""

  # Centrifugo api_key for Centrifugo API endpoint authorization.
  apiKey: ""

  # Centrifugo grpc_api_key for Centrifugo GRPC API authorization.
  grpcApiKey: ""

  # Connection string to Redis.
  redisUrl: ""

  # Password for Redis.
  redisPassword: ""

  # Password for Redis Sentinel.
  redisSentinelPassword: ""

  # Connection string to Nats.
  natsUrl: ""

# Additional environment variables to be passed to Centrifugo container.
env: {}
