replicaCount: 1

image:
  repository: centrifugo/centrifugo
  tag: v2.6.2
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  port: 8000
  type: ClusterIP
  # Static NodePort, if set.
  # nodePort: 30100

internalService:
  enabled: true
  port: 9000
  type: ClusterIP
  # Static NodePort, if set.
  # nodePort: 30100

grpcService:
  enabled: false
  port: 10000
  type: ClusterIP
  # Static NodePort, if set.
  # nodePort: 30100

ingress:
  enabled: false
  # example on how to run with custom path prefix:
  # annotations:
  #   nginx.ingress.kubernetes.io/rewrite-target: /$2
  # path: /prefix(/|$)(.*)
  annotations: {}
  path: /
  hosts: []
  # https://kubernetes.github.io/ingress-nginx/examples/tls-termination/
  tls: []

resources: {}

serviceAccount:
  # Specifies whether a service account should be created
  enabled: false
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

# Role-based Access Control
rbac:
  # Specifies whether RBAC resources should be created
  enabled: false

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

terminationGracePeriodSeconds: 30

podAnnotations: {}

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

deploymentStrategy: {}
  # type: RollingUpdate
  # rollingUpdate:
  #   maxSurge: 0
  #   maxUnavailable: 1

serviceMonitor:
  enabled: false
  # namespace: monitoring
  # interval: 10

  # Set labels for the ServiceMonitor, use this to define your scrape label for Prometheus Operator
  labels: {}

nodeSelector: {}

tolerations: []

affinity: {}

config:
  log_level: "debug"

  # Engine to use. Default memory engine allows running only one Centrifugo pod
  # Scale to many pods with Redis engine or Nats broker. Refer to Centrifugo
  # documentation: https://centrifugal.github.io/centrifugo/server/engines/
  engine: "memory"

  # Broker to use, not used by default.
  broker: ""

  # Use offset protocol field.
  v3_use_offset: true

  # Enable admin web interface by default.
  admin: true

  # Array of namespaces.
  namespaces: []

secrets:
  # Secret key for HMAC tokens.
  tokenHmacSecretKey: ""

  # Admin password used to protect access to web interface.
  adminPassword: ""

  # Admin secret used to create auth tokens on user login into admin web interface.
  adminSecret: ""

  # Centrifugo api_key for Centrifugo API endpoint authorization.
  apiKey: ""

  # Centrifugo grpc_api_key for Centrifugo GRPC API authorization.
  grpcApiKey: ""

  # Connection string to Redis.
  redisUrl: ""

  # Password for Redis.
  redisPassword: ""

  # Password for Redis Sentinel.
  redisSentinelPassword: ""

  # Connection string to Nats.
  natsUrl: ""

# additional environment variables to be passed to Centrifugo container.
env: {}
